### ISSUE TITLE
Is it Compatible with Presence of the Foodstep and others?

### ISSUE THREAD

**Issue by ardissaps** [Sydokiddo/auditory#1]
https://modrinth.com/mod/presence-footsteps
https://modrinth.com/mod/extrasounds
https://modrinth.com/mod/charmonium
Thank you very much

**Comment by Sydokiddo** [comment]
It should work fine!

**Comment by ardissaps** [comment]
> It should work fine!

I just figured out that it isn't available for 1.18.2.
Many of my mods not yet ready for 1.19 :(
