### ISSUE TITLE
ItemDropSoundMixin causes incompatibility with other mods

### ISSUE THREAD

**Issue by Devoev** [Sydokiddo/auditory#11]
The way the drop method in ItemDropSoundMixin is implemented causes the mod to be incompatible with other mods, that also try to modify the Players drop method. Just injecting the extra code into the method at the desired place instead of completely overriding the vanilla method should fix this problem

**Comment by Sydokiddo** [comment]
Thank you! Will take a look at this and fix it as soon as possible!

**Comment by Sydokiddo** [comment]
Fixed in version 0.0.4!
