### ISSUE TITLE
[BUG] Some sounds not working in multiplayer

### ISSUE THREAD

**Issue by MarkinhosMLP** [Sydokiddo/auditory#12]
as it says in the mod page  

"A: As of v0.0.3, the mod also needs to be installed on the server for specific sounds to work and sync with the client!

Certain things like block sounds and such should work completely client-side, but other features such as item interaction sounds and such will need for the mod to be installed server-side as well."

the problem is that a lot of block sounds is not working in multiplayer, for example ice variants, obsidian and bricks, pistons, torches and others

**Comment by MarkinhosMLP** [comment]
no sounds or almost no sound works in multiplayer.....

**Comment by Sydokiddo** [comment]
Are you using any other mods, and what Minecraft version are you using?

**Comment by MarkinhosMLP** [comment]
im using a lot of other mods, minecraft 1.19.2
tried only with optifine, presence footsteps and auditory and it still not working, just in singleplayer worlds

**Comment by Sydokiddo** [comment]
Could be an issue with Optifine possibly, as Optifine is closed source and generally unreliable for support with Fabric mods, because I have tested it on multiplayer plenty of times and it should work fine

**Comment by MarkinhosMLP** [comment]
forgot to say but i also play using dynamic surroundings which also works with sounds, and afaik it isnt incompatible but who knows

ill try without optifine and ill come back to say about it

**Comment by MarkinhosMLP** [comment]
without optifine, stills no sounds in multiplayer :((( this is sad, now its time to try without dynamic

**Comment by MarkinhosMLP** [comment]
without dynamic surroundings stills not working in multiplayer....

let me try without dynamic sound filters and sound muffler

**Comment by MarkinhosMLP** [comment]
nothing worked... have to try without presence footsteps now

**Comment by MarkinhosMLP** [comment]
nothing. stills not working in multiplayer
now ill try just the auditory mod and its dependencies

**Comment by MarkinhosMLP** [comment]
yea seems like actually NO FEATURES work in client side only... 
its 100% necessary to have both client and server side
