### ISSUE TITLE
[CRITICAL] MALWARE IN 0.0.2 DOWNLOAD

### ISSUE THREAD

**Issue by MarkinhosMLP** [Sydokiddo/auditory#13]
since my last report in 0.0.3 i tried to download 0.0.2 version in modrinth, then my computer started glitching, appearing jumpscares and opening a lot of suspicious links

yesterday my computer was fine, today i downloaded nothing but Auditory 0.0.2 in Modrinth

when i deleted the jar, all of that suspicious virus stuff disappeared and stopped happening

**Comment by MarkinhosMLP** [comment]
ill try the curseforge one then ill be back here if it dont break my computer lol

**Comment by MarkinhosMLP** [comment]
it cleared all my minecraft launcher configurations and saves too...

**Comment by MarkinhosMLP** [comment]
apparently the curseforge version does not have the same issue

**Comment by Sydokiddo** [comment]
I'm gonna need evidence of this because I genuinely have no idea how that could even happen nor has this happened to anyone else

**Comment by MarkinhosMLP** [comment]
I have no idea of how i could give evidences of it without damaging my computer again... i just recommend to reupload the file or try in a fake virtual computer

**Comment by Sydokiddo** [comment]
Yeah, I'm gonna be honest, I've tried it myself and there's absolutely no malware on the mod, so my guess is that you somehow downloaded something else that harmed your computer, because other than that I cannot recreate this issue and don't know what else to say
