### ISSUE TITLE
Stone sounds play when you're on the edge of blocks that aren't stone

### ISSUE THREAD

**Issue by Reyitos64** [Sydokiddo/auditory#14]
this is in the latest version, no other mods are present.

https://user-images.githubusercontent.com/103141010/196797700-067218ce-d8c5-454a-b541-22621b560481.mp4

**Comment by Reyitos64** [comment]
just learned that this is caused by the misc sound "Jumping on a block in place". an option to disable this similar to the rest of the sounds in this mod would be appreciated :)

**Comment by Sydokiddo** [comment]
I believe this is due to it playing the sound of air blocks which defaults to the stone sound I'd imagine, I could probably add a method to not count air blocks for the sound, thank you!

**Comment by Sydokiddo** [comment]
Fixed in version 0.0.4!
