### ISSUE TITLE
Sounds not working in ClientSide anymore

### ISSUE THREAD

**Issue by MarkinhosMLP** [Sydokiddo/auditory#16]
0.0.3 say it is not exclusively client side anymore, but now it is 100% necessary to have the mod in both client and server sides
no sounds works in multiplayer if the server doesnt have the mod, not even placing blocks which should work fine (at least thats what it says in the 0.0.3 changelog)

i thought it could be incompatibility error as i reported in #12 but tried again and again, removing a lot of mods and then, tried with no mods but Auditory and Fabric API and stills not working, just in singleplayer worlds

**Comment by Sydokiddo** [comment]
The new data-driven system won't allow tags to be loaded specifically client-side, so yes, you will need the mod on the server for block sounds to work properly!

**Comment by MarkinhosMLP** [comment]
> The new data-driven system won't allow tags to be loaded specifically client-side, so yes, you will need the mod on the server for block sounds to work properly!

so the mod is now useless if i use only client side :( thats bad

**Comment by MariobrosU22** [comment]
oh sad
