### ISSUE TITLE
Overlapping sounds with ExtraSounds mod

### ISSUE THREAD

**Issue by Zartrix** [Sydokiddo/auditory#2]
Using Auditory and ExtraSounds dropping an item plays both drop sounds added by each mod.
Maybe adding a config could help here?

**Comment by Sydokiddo** [comment]
Good idea, I'll try and make sure it disables the drop sound if ExtraSounds is installed

**Comment by Sydokiddo** [comment]
ModMenu compatibility added in the next upcoming version!

**Comment by spaghettube** [comment]
seems like the dropping sounds from extrasounds and auditory are overlapping by default. im using auditory 0.0.4 and extrasounds 2.3.1 both for 1.19.2 (fabric). you can use modmenu to disable the dropping sound from auditory, but it isn't off by default.
