### ISSUE TITLE
Add Support for the Friends and Foes Mod

### ISSUE THREAD

**Issue by KevinCCucumber** [Sydokiddo/auditory#20]
Hey, I would really like to enjoy this mod with besser sounds. They are almost vanilla. Is this interesting to you?
Is it possible to add those sounds to the pack?

The Mod in question is this one: https://github.com/Faboslav/friends-and-foes

**Comment by sydneybeanmc** [comment]
What support does there need to be for Friends and Foes? It should work fine with it
