### ISSUE TITLE
Extrasounds compatibility

### ISSUE THREAD

**Issue by pocinhas** [Sydokiddo/auditory#21]
Hey there. I saw that you had fixed this before so I reckoned I'd report it since it's happening again. Auditory doesn't disable player.item.drop by default when extrasounds is installed in the same instance.
https://user-images.githubusercontent.com/101492556/203864988-67d90a2f-0007-4107-82a3-717ab382745c.mp4

**Comment by sydneybeanmc** [comment]
![caption](https://user-images.githubusercontent.com/94016034/203945793-41a803ff-f757-49e7-a9c3-cf68263301d5.gif)
