### ISSUE TITLE
Add 1.19.3 version compatibility

### ISSUE THREAD

**Issue by Vi-Tul** [Sydokiddo/auditory#23]

**Comment by sydneybeanmc** [comment]
This isn't an issue, be patient lol the update just came out

**Comment by dinhero21** [comment]
Is it compatible with 1.19.3 yet? I tried it on 1.19.3 and it crashed. I don't know if that is a bug or intended.

**Comment by sydneybeanmc** [comment]
No, it doesn't work on 1.19.3 yet, a port will come eventually though

**Comment by dinhero21** [comment]
k

**Comment by Aces-and-Jacks** [comment]
What about keeping this open so others can see it and once the mod does get updated then close it?
