### ISSUE TITLE
Incompatibility with Bow Infinity Fix

### ISSUE THREAD

**Issue by Ed-Salt** [Sydokiddo/auditory#24]
For some reason, when this mod and [Bow Infinity Fix](https://www.curseforge.com/minecraft/mc-mods/bow-infinity-fix) are present, the mod doesn't function and you still need an arrow in your inventory to shoot an infinity enchanted bow.

**Comment by MrLoLf** [comment]
Can you provide the latest.log where this error has happened to you, with that it would be easier to troubleshoot this.

**Comment by sydneybeanmc** [comment]
Should hopefully be fixed as of 0.0.5, do let me know if there are any issues!
