### ISSUE TITLE
Latest Modrinth version 0.0.4 does not have Quilt specified

### ISSUE THREAD

**Issue by theRookieCoder** [Sydokiddo/auditory#27]
A rather small thing for a GitHub Issue, but I was unable to contact you any other way so here we are. The latest [`0.0.4` release](https://modrinth.com/mod/auditory/version/0.0.4) doesn't seem to flag compatibility with Quilt. This leads to issues because your previous version does flag compatibility with Quilt, leading to that being downloaded instead of the latest version when filtering for Quilt.

**Comment by sydneybeanmc** [comment]
Fixed!
