### ISSUE TITLE
Seperate Block-Sounds.

### ISSUE THREAD

**Issue by laitz** [Sydokiddo/auditory#30]
So I love this mod but I'm just curious why it isn't possible to turn off individual block sounds. I like most of them but the Shulker one is bothering me :P

**Comment by laitz** [comment]
So maybe the suggestion here is that there should be more specific block sound configs.

**Comment by sydneybeanmc** [comment]
Could eventually implement this, good idea!

**Comment by sydneybeanmc** [comment]
Done as of 0.0.5!
