### ISSUE TITLE
Client gets kicked whenever interacting with the world w/ Auditory on server side

### ISSUE THREAD

**Issue by zndrmn** [Sydokiddo/auditory#34]
Clients without auditory get kicked after a little bit when joining a server with auditory installed

![image](https://user-images.githubusercontent.com/77690119/225520539-ba2fd980-59af-4515-95ff-cc12d1614227.png)

**Comment by sydneybeanmc** [comment]
For servers that have Auditory installed, the client will also need it as it adds new sound events that play on both the server and client
