### ISSUE TITLE
No sounds on server

### ISSUE THREAD

**Issue by Meelee35** [Sydokiddo/auditory#39]
This has been answered a million times before, but here i am. Well lets cut to the point shall we.

On the auditory curseforge page it states that SOME sounds will still work clientside when the mod is not installed on the server, but in replies to previous issues of similar type you stated that block sounds will not work, whereas the curseforge page said they did.

Please update your curseforge page to tell us what  sounds will and will not work when the mod is not installed on a server.

**Comment by sydneybeanmc** [comment]
Will update this as soon as possible, thank you for mentioning this!
