### ISSUE TITLE
Some sounds are not working

### ISSUE THREAD

**Issue by Saileeich** [Sydokiddo/auditory#4]
When in singleplayer, sounds such as items dropping or a bow pulling back will only play every other time. On my server, which is using a prox chat mod, the item dropping sound is not played and the bow pulling back is still only every other time. Everything else I have experimented with has worked wonderfully so far, it's just those two sounds that are bugged for me.

**Comment by spaghettube** [comment]
Hey there! Just wanted to let you know that the enderpearl teleport sound also does not work on multiplayer

**Comment by Sydokiddo** [comment]
Fixed as of v0.0.3
