### ISSUE TITLE
`#auditory:leaf_sounds` should use `#minecraft:leaves` tag and `#minecraft:saplings` block tags

### ISSUE THREAD

**Issue by thelegitdolt** [Sydokiddo/auditory#47]

**Comment by thelegitdolt** [comment]
this will allow for greater mod compatability out the gate

**Comment by sydneybeanmc** [comment]
Good idea, will keep this in mind!

**Comment by thelegitdolt** [comment]
In addition to this, i believe plant sounds could parent `#minecraft:small_flowers` and `#minecraft:large_flowers`
