### ISSUE TITLE
Problems with the ExtraSounds mod and crash minecraft

### ISSUE THREAD

**Issue by DaniruAnime** [Sydokiddo/auditory#5]
The mod reproduces sounds together with the Extra Sounds mod (the sound of pulling a bow and dropping an item). Minecraft crashes if insert or pull out any record from the player. Quilt Minecraft 1.19 is used. The crash report is attached.

Sorry, I don't know English well and use machine translation.
[crash-2022-07-23_12.07.53-client.txt](https://github.com/Sydokiddo/auditory/files/9175044/crash-2022-07-23_12.07.53-client.txt)

**Comment by Sydokiddo** [comment]
For the issue with Extra Sounds, the bow pulling and item dropping sounds can be disabled via the config if you have ModMenu installed

For the issue with the Jukebox, I will take a look at it!

**Comment by DaniruAnime** [comment]
Ok

**Comment by Sydokiddo** [comment]
Fixed as of v0.0.3
