### ISSUE TITLE
[SUGGESTION] Option to disable swinging sound on block destruction.

### ISSUE THREAD

**Issue by kirmerk1** [Sydokiddo/auditory#8]
Love the new update. Swinging sounds are soft and nice, but when you use pickaxe and other tools a lot, it's too much. Would be great, if it swing only when hit air or mobs etc. Toggle for each tool would be cool too, because breaking anything with sword sounds cool.

**Comment by Sydokiddo** [comment]
There is already a toggle for each tool if ModMenu is installed

Also, I do want to change it to only play the sound when swinging in the air if I can find a proper way to detect swinging in the air if possible!
